/*
 * This source file was generated by the Gradle 'init' task
 */
package com.todo;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class AppTest {

    @Test
    public void testGreeting() {
        App app = new App();
        String greeting = app.getGreeting();
        assertNotNull(greeting, "Greeting should not be null");
        assertFalse(greeting.trim().isEmpty(), "Greeting should not be empty");
    }
}
